### ISSUE TITLE
Desenvolver Estrutura do Frontend 

### ISSUE THREAD

**Issue by angeliski** [angeliski/frontendbr-eventos-api#13]
É necessário desenvolver a estrutura do front para consumo da API. É preciso decidir se vamos usar anguar, react, webpack e afins.

**Comment by mesafael** [comment]
@angeliski como meu conhecimento com Node e pouco ainda, acho que posso ajudar nesse ponto(Front), ja tem uma definição sobre?
Pode definir alguma coisa ? acho melhor, porque assim tenho uma base para iniciar!

**Comment by angeliski** [comment]
Legal @mesafael Você tem experiência com alguma dessas tecnologias? A ideia é você desenvolver naquela que te deixar mais confortável, assim a sua produtividade pode ser maior. Ou, caso você não tenha experiência com elas (eu mesmo não tenho), qual delas você tem vontade de estudar? Assim isso se torna uma porta pra você desenvolver uma skill nova e contribuir.

**Comment by mesafael** [comment]
Ja tenho experiencia com Angular1, ja vi algumas coisas sobre o Angular2+ acredito que posso trabalhar com ele.

**Comment by angeliski** [comment]
Então a gente pode seguir assim cara. Iniciar o projeto usando Angular2+, tendo em mente a ideia de PWA. Você pode iniciar trabalhando com dados fake e depois eu te ajudo na integração da API.
O que precisa é:

- Um  form de cadastro
-  Uma listagem dos eventos (pendentes, mas tem uma url especifica pra isso)
- Na listagem o usuário pode aprovar ou reprovar o evento

No seu mock, você pode inclusive usar o JSON que o site já consome hoje, porque eu tentei manter a mesma estrutura: https://github.com/frontendbr/eventos/blob/develop/src/data/events.json

**Comment by angeliski** [comment]
@mesafael  Ah! Se você precisar, eu te dou acesso ao repositório e você pode criar as issues aqui mesmo, pra gente manter o controle

**Comment by angeliski** [comment]
Ae @mesafael Eu criei uma branch com uma estrutura do Angular2+ integrado no server do express que a gente já usa hoje. Você pode só validar ela pra mim? Eu usei esse bolerplaite aqui: https://github.com/lamecoder/angular2-node-express-webpack
Porque eu não manjo de Angular2 nem de webpack... XD
Tem uns dois componentes já prontos lá, ai você validando eu faço o merge na master pra gente já seguir nessa nova separação. Pode ser? Ps. se você tiver outra ideia, fique a vontade para sugerir

**Comment by mesafael** [comment]
@angeliski acho que seria melhor o padrão ng-cli não? não manjo muito de Git ainda estava com duvida de como iniciar o projeto rsrs.

poderia me passar uma forma de contato so pra me tirar umas duvidas basicas(seria de estrutura o Git)?

**Comment by angeliski** [comment]
@mesafael Eu só usei esse boilerplate por conta da configuração do webpack, porque eu queria empacotar o sever eo front em um start só, facilitando o esquema pra desenvolvimento. Mas acho que disponibilizar o ng-cli naquela pasta de client é relativamente simples.
Se você quiser pode me mandar um email, angeliski@hotmail.com, ou ir me perguntando aqui que eu vou respondendo. Se você der um clone no projeto e usar a branch **feature-estrutura-front-end** é só rodar um npm install na raiz e depois um npm start. Assim a aplicação vai estar disponivel em http//localhost:3000

**Comment by mesafael** [comment]
Perfeito @angeliski projeto rodo aqui normalmente, acho que ja consigo dar continuidade.

Fora aqueles ponto que voce ja passo tem algum outro, Questão visual e tals...

**Comment by angeliski** [comment]
Cara, eu não tenho nenhuma consideração visual, acho seu que você pode tocar como achar melhor. Só lembrando(que eu não lembro se disse) é que essa aplicação é acessada por dois perfis, normal e adim. O normal só vai ver o form de cadastro dos eventos, enquanto o administrador também pode ver os eventos para aprovação. 
No mais, se precisar me dá um toque :)

**Comment by angeliski** [comment]
@mesafael Eu posso fazer o merge dessa branch na master? Assim a gente segue com essa estrutura de webpack e você pode gerar outras branchs para o cadastro e afins. Pode ser?

**Comment by mesafael** [comment]
@angeliski tentei iniciar ontem, tive alguns problemas com estrutura(nome da pasta src) e versão do angular cli.
Mais no final conseguir resolver!

So pra ficar laro, vou usar Material Design com o [Materialize](materializecss) beleza?

**Comment by angeliski** [comment]
Sem problemas cara. Só uma observação, eu tive problemas usando o materialize na versão um... Várias questões de render que eu tive que tratar com uns digests da vida... Mas toca pau ai mano

**Comment by angeliski** [comment]
@mesafael Eu vou fazer o merge da branch na master!

**Comment by mesafael** [comment]
@angeliski estou com alguns problemas que não consigo resolver.

Pelo que procurei são erros de versão do Angular e Estruturais.

- Erros como fazer chamada de CSS e JS pelo .angular-cli.json
- E rotas das paginas.

Vou realizar um commit acredito que seria interessante alguém com um pouco mais de experiencia com o Angular2+ so pra da uma olhada rsrs.

**Comment by angeliski** [comment]
Opa! Comita ai que eu dou uma olhada, se não souber resolver a gente pede ajuda. XD

**Comment by angeliski** [comment]
@mesafael Quando você comitar me avisa que eu dou uma olhada

**Comment by mesafael** [comment]
Estou com um pouco de dificuldade aqui com o Git kkkk

Devo subir na branch e não na master ne?

**Comment by angeliski** [comment]
De boas cara. Você tem Face? Me add lá que eu te dou uma força pelo messenger: https://www.facebook.com/Angeliskii

**Comment by angeliski** [comment]
Por estar estudando Vue.js, eu optei por criar uma estrutura que eu possa criar e estudar alguns padrões.
Segue o repositório: https://github.com/angeliski/frontendbr-eventos-portal

**Comment by angeliski** [comment]
A estrutura inicial foi definida no repositório, as issues relacionadas ao front, serão tratadas lá.
